version: '3.4'

services:
  technationdashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - sqlserver
    volumes:
      - dataprotection-keys:/root/.aspnet/DataProtection-Keys

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "StrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

volumes:
  dataprotection-keys:
